---
- name: install cloud provider client binaries as well as PKI server, cryptography, and compiling tools
  hosts: cryptest
  tasks:

  - name: shell install packages
    shell: apt-get install docker.io docker-compose tcpdump ca-certificates certbot python3.10-venv lsb-release apt-transport-https golang git g++ unzip zip curl wget openjdk-11-jdk gnupg2 age vim openssl gcc -y
    args:
      executable: /bin/bash

  - name: shell configure bazel key
    shell: curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && mv bazel-archive-keyring.gpg /usr/share/keyrings && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    args:
      executable: /bin/bash
      
  - name: shell install bazel
    shell: apt-get update -y && apt-get install bazel -y
    args:
      executable: /bin/bash      
      
  - name: shell git clone wycheproof
    shell: rm -rf wycheproof 2>/dev/null && git clone https://github.com/google/wycheproof.git
    args:
      executable: /bin/bash  

  - name: shell rustup
    shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh && sh ./rustup.sh -y
    args:
      executable: /bin/bash  

  - name: install step
    shell: wget https://dl.step.sm/gh-release/cli/docs-ca-install/v0.21.0/step-cli_0.21.0_amd64.deb && dpkg -i step-cli_0.21.0_amd64.deb
    args:
      executable: /bin/bash  

  - name: install step-ca
    shell: wget https://dl.step.sm/gh-release/certificates/docs-ca-install/v0.21.0/step-ca_0.21.0_amd64.deb && dpkg -i step-ca_0.21.0_amd64.deb
    args:
      executable: /bin/bash  

  - name: shell install kubectl client
    shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    args:
      executable: /bin/bash  

  - name: shell install aws cli
    shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    args:
      executable: /bin/bash  

  - name: shell install gcp repo
    shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    args:
      executable: /bin/bash  

  - name: shell install gcp package key
    shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    args:
      executable: /bin/bash 

  - name: shell install gcp 
    shell: apt-get update -y && apt-get install google-cloud-cli -y
    args:
      executable: /bin/bash

  - name: shell install azure package key
    shell: curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
    args:
      executable: /bin/bash  

  - name: shell install azure repo
    shell: AZ_REPO=$(lsb_release -cs); echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
    args:
      executable: /bin/bash      

  - name: shell install azure cli
    shell: apt-get update -y && apt-get install azure-cli -y
    args:
      executable: /bin/bash        
     
  - name: shell install hasicorp vault package key
    shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
    args:
      executable: /bin/bash     

  - name: shell install hasicorp vault repo
    shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    args:
      executable: /bin/bash     

  - name: shell install hasicorp vault
    shell: apt-get update -y && apt-get install vault -y
    args:
      executable: /bin/bash  

  - name: shell install trivy package key
    shell: wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
    args:
      executable: /bin/bash  
    
  - name: shell install trivy repo
    shell: echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    args:
      executable: /bin/bash      

  - name: shell install trivy
    shell: apt-get update && apt-get install trivy -y
    args:
      executable: /bin/bash  

  - name: shell install syft
    shell: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    args:
      executable: /bin/bash  

  - name: shell install cosign
    shell: get "https://github.com/sigstore/cosign/releases/download/v1.6.0/cosign_1.6.0_amd64.deb" && dpkg -i "cosign_1.6.0_amd64.deb
    args:
      executable: /bin/bash  
 
  - name: shell install cargo clippy
    shell: rustup component add clippy
    args:
      executable: /bin/bash    
   
...
